import { useEffect, useState } from 'react';
import { AlertTriangle, Check, Download, ExternalLink, Github, Plus, RefreshCw, Save, Trash2, X } from 'lucide-react';
import { api } from '../lib/api';
import { currentYear, formatDateTime, TIME_ZONE_OPTIONS, timeZoneLabel } from '../lib/date';
import { exportHeatmap } from '../lib/export';
import { PLATFORM_META, PLATFORM_ORDER } from '../lib/platforms';
import { emptyAccounts, scopeRange, type AccountMap } from '../lib/ui';
import type { Metric, Platform, SyncStatus } from '../types';

export function SettingsPage({ accounts, timeZone, onTimeZone, onSaved }: { accounts: AccountMap; timeZone: string; onTimeZone: (value: string) => void; onSaved: () => void }) {
  const [form, setForm] = useState<AccountMap>(emptyAccounts); const [saving, setSaving] = useState(false);
  useEffect(() => { const next = emptyAccounts(); for (const platform of PLATFORM_ORDER) next[platform] = accounts[platform].length ? accounts[platform].map((entry) => ({ ...entry })) : [{ platform, account: '', secret: '' }]; setForm(next); }, [accounts]);
  const change = (platform: Platform, index: number, key: 'account' | 'secret', value: string) => setForm((current) => ({ ...current, [platform]: current[platform].map((entry, row) => row === index ? { ...entry, [key]: value } : entry) }));
  const add = (platform: Platform) => setForm((current) => ({ ...current, [platform]: [...current[platform], { platform, account: '', secret: '' }] }));
  const remove = (platform: Platform, index: number) => setForm((current) => { const rows = current[platform].filter((_, row) => row !== index); return { ...current, [platform]: rows.length ? rows : [{ platform, account: '', secret: '' }] }; });
  const save = async () => { setSaving(true); try { for (const platform of PLATFORM_ORDER) await api.saveAccounts(platform, form[platform].filter((entry) => entry.account.trim())); await onSaved(); } finally { setSaving(false); } };
  return <><header className="topbar"><div><small>ACCOUNTS</small><h1>账号设置</h1><p>同一平台可以添加多个 ID，统计时可汇总，也可在平台页单独查看。</p></div><button className="primary" onClick={save} disabled={saving}><Save size={16} />{saving ? '保存中' : '保存设置'}</button></header><section className="settings-intro"><strong>怎么填写？</strong><span>填写个人主页 URL 中的账号标识，不是显示昵称。Cookie 仅在对应平台需要登录数据时填写，全部只保存在本机。</span></section><section className="panel timezone-card"><div><small>STATISTICS TIME ZONE</small><h2>统计时区</h2><p>提交保留原始时间，活动砖、今日进度、连续打卡和问候语会按所选时区即时换算。</p></div><label><span>当前时区</span><select value={timeZone} onChange={(event) => onTimeZone(event.target.value)}>{TIME_ZONE_OPTIONS.map(([value, label]) => <option value={value} key={value}>{label} · {value}</option>)}</select><small>{timeZoneLabel(timeZone)}</small></label></section><section className="account-panel">{PLATFORM_ORDER.map((platform) => <article className="account-card" key={platform}><div className="account-card-head"><div><span className="platform-monogram" style={{ color: PLATFORM_META[platform].accent }}>{PLATFORM_META[platform].short}</span><div><strong>{PLATFORM_META[platform].name}</strong><small>{PLATFORM_META[platform].accountHint}</small></div></div><button onClick={() => add(platform)}><Plus size={14} />添加 ID</button></div><div className="account-inputs">{form[platform]?.map((entry, index) => <div className="account-entry" key={index}><span>{index + 1}</span><input value={entry.account} onChange={(event) => change(platform, index, 'account', event.target.value)} placeholder={PLATFORM_META[platform].accountHint} />{PLATFORM_META[platform].secretHint ? <input type="password" value={entry.secret} onChange={(event) => change(platform, index, 'secret', event.target.value)} placeholder={PLATFORM_META[platform].secretHint} autoComplete="off" /> : <small>公开数据，无需密码</small>}<button className="remove-account" onClick={() => remove(platform, index)} aria-label="移除账号"><X size={14} /></button></div>)}</div></article>)}</section></>;
}
export function DataPage({ statuses, syncing, timeZone, onSync, onSyncAll, onCleared, notify }: { statuses: SyncStatus[]; syncing: string | null; timeZone: string; onSync: (platform: Platform, full?: boolean) => void; onSyncAll: () => void; onCleared: () => void; notify: (message: string) => void }) {
  const by = new Map(statuses.map((status) => [status.platform, status]));
  const clearOne = async (platform: Platform) => { if (!confirm(`清空 ${PLATFORM_META[platform].name} 的全部本地记录？账号设置会保留。`)) return; await api.clearPlatform(platform); notify('已清空'); onCleared(); };
  const clearAll = async () => { if (!confirm('清空所有 OJ 的本地记录？账号设置会保留。')) return; await api.clearAll(); notify('所有本地记录已清空'); onCleared(); };
  return <><header className="topbar"><div><small>SYNC & LOCAL DATA</small><h1>同步与数据</h1><p>同步失败不会删除旧记录；“重建”用于重新读取该平台的完整历史。</p></div><button className="primary" onClick={onSyncAll} disabled={!!syncing}><RefreshCw size={16} className={syncing ? 'spin' : ''} />同步全部</button></header><section className="panel source-list">{PLATFORM_ORDER.map((platform) => { const status = by.get(platform); return <article key={platform}><div className="source-id"><span className="platform-monogram" style={{ color: PLATFORM_META[platform].accent }}>{PLATFORM_META[platform].short}</span><div><strong>{PLATFORM_META[platform].name}</strong><small>{status?.account || '未配置账号'} · 缓存 {status?.cached_records || 0} 条</small></div></div><div className={`source-state ${status?.status || 'idle'}`}>{status?.status === 'ok' ? <Check size={15} /> : status?.status === 'error' || status?.status === 'auth_required' ? <AlertTriangle size={15} /> : null}<div><strong>{syncStatusLabel(status?.status)}</strong><small>{status?.message || '尚未同步'} · 上次成功 {formatDateTime(status?.last_success || null, timeZone)}</small></div></div><div className="source-actions"><button onClick={() => onSync(platform)} disabled={!!syncing}><RefreshCw size={14} />增量</button><button onClick={() => onSync(platform, true)} disabled={!!syncing}>重建</button><button className="danger-ghost" onClick={() => clearOne(platform)}><Trash2 size={14} />清空</button></div></article>; })}</section><section className="danger-zone"><div><strong>清空全部训练数据</strong><p>会删除提交、活动砖和同步状态，账号设置不会被删除。</p></div><button onClick={clearAll}><Trash2 size={15} />清空全部</button></section></>;
}

function syncStatusLabel(status?: string) { return ({ idle: '未同步', syncing: '同步中', ok: '同步成功', warning: '部分成功', error: '同步失败', auth_required: '需要重新登录' } as Record<string, string>)[status || 'idle'] || status || '未同步'; }

export function ExportPage({ accounts, metric, timeZone }: { accounts: AccountMap; metric: Metric; timeZone: string }) {
  const [from, setFrom] = useState(currentYear(timeZone) - 2); const [to, setTo] = useState(currentYear(timeZone)); const [until, setUntil] = useState(false); const [scope, setScope] = useState<'all' | Platform>('all'); const [format, setFormat] = useState<'png' | 'svg'>('png'); const [busy, setBusy] = useState(false);
  const years = Array.from({ length: currentYear(timeZone) - 2009 }, (_, index) => 2010 + index);
  const run = async () => { setBusy(true); try { const range = until ? scopeRange('until', timeZone) : { start: `${from}-01-01`, end: `${to}-12-31` }; const snap = await api.snapshot(scope === 'all' ? null : scope, range.start, range.end, metric, null, null, timeZone); await exportHeatmap(`OJ Insight · ${scope === 'all' ? '所有 OJ' : PLATFORM_META[scope].name} · ${until ? '至今（近一年）' : `${from}–${to}`}`, snap.daily, until ? Number(range.start.slice(0, 4)) : from, until ? Number(range.end.slice(0, 4)) : to, format, range.start, range.end); } finally { setBusy(false); } };
  return <><header className="topbar"><div><small>EXPORT</small><h1>活动砖导出</h1><p>原有 PNG、SVG、单平台与合并导出全部保留。</p></div></header><div className="export-layout"><section className="panel export-form"><label>范围<div className="segmented"><button className={!until ? 'active' : ''} onClick={() => setUntil(false)}>年份区间</button><button className={until ? 'active' : ''} onClick={() => setUntil(true)}>至今</button></div></label>{!until && <label>年份<div className="range-row"><select value={from} onChange={(event) => setFrom(Number(event.target.value))}>{years.map((year) => <option key={year}>{year}</option>)}</select><span>—</span><select value={to} onChange={(event) => setTo(Number(event.target.value))}>{years.map((year) => <option key={year}>{year}</option>)}</select></div></label>}<label>平台<select value={scope} onChange={(event) => setScope(event.target.value as 'all' | Platform)}><option value="all">所有 OJ 合并</option>{PLATFORM_ORDER.map((platform) => <option key={platform} value={platform} disabled={!accounts[platform].length}>{PLATFORM_META[platform].name}</option>)}</select></label><label>格式<div className="segmented"><button className={format === 'png' ? 'active' : ''} onClick={() => setFormat('png')}>PNG</button><button className={format === 'svg' ? 'active' : ''} onClick={() => setFormat('svg')}>SVG</button></div></label><button className="primary export-btn" onClick={run} disabled={busy || (!until && from > to)}><Download size={16} />{busy ? '生成中…' : '选择位置并导出'}</button></section><section className="panel export-preview"><div className="mock-export"><div><strong>OJ Insight · 活动砖</strong><small>{until ? '至今' : `${from} — ${to}`}</small></div><div className="mock-grid">{Array.from({ length: 160 }).map((_, index) => <i key={index} className={`level-${(index * 17 + index * index) % 5}`} />)}</div><span>{scope === 'all' ? '所有 OJ' : PLATFORM_META[scope].name}</span></div></section></div></>;
}

export function AboutPage() {
  const [update, setUpdate] = useState<Awaited<ReturnType<typeof api.checkForUpdates>> | null>(null); const [checking, setChecking] = useState(false); const [error, setError] = useState(''); const [storage, setStorage] = useState<Awaited<ReturnType<typeof api.storageInfo>> | null>(null);
  useEffect(() => { api.storageInfo().then(setStorage).catch(() => undefined); }, []);
  const check = async () => { setChecking(true); setError(''); try { setUpdate(await api.checkForUpdates()); } catch (value) { setError(String(value)); } finally { setChecking(false); } };
  return <><header className="topbar"><div><small>ABOUT</small><h1>关于 OJ Insight</h1><p>把分散在多个 Online Judge 的训练轨迹，整理成一份属于你的本地记录。</p></div></header><section className="about-layout"><article className="panel about-card"><div className="about-mark">OI</div><h2>OJ Insight</h2><p>版本 0.4.0 · Local-first</p>{update ? <div className={update.updateAvailable ? 'update-state available' : 'update-state'}><strong>{update.updateAvailable ? `发现新版本 · v${update.latestVersion}` : '当前已是最新版本'}</strong>{update.updateAvailable && <button onClick={() => api.openExternal(update.releaseUrl)}>查看发布页 <ExternalLink size={14} /></button>}</div> : <button className="primary" onClick={check} disabled={checking}><RefreshCw size={15} className={checking ? 'spin' : ''} />{checking ? '正在检查' : '检查更新'}</button>}{error && <div className="warning"><AlertTriangle size={15} />{error}</div>}<div className="about-links"><button onClick={() => api.openExternal('https://github.com/Whalica/OJ_Insight')}><Github size={16} />GitHub 仓库<ExternalLink size={13} /></button><button onClick={() => api.openExternal('https://github.com/Whalica/OJ_Insight/issues')}><AlertTriangle size={16} />Issue 反馈<ExternalLink size={13} /></button></div></article><article className="panel storage-card"><small>YOUR DATA</small><h2>数据放在哪里？</h2><p>OJ Insight 把账号设置、同步记录和导出文件集中放在应用自己的便携目录里。迁移电脑时，只需要一起复制这个目录。</p><div><strong>训练记录</strong><span>账号设置、提交记录、活动与难度统计</span></div><div><strong>导出内容</strong><span>你生成的 PNG 与 SVG 文件</span></div><div><strong>运行记录</strong><span>遇到同步问题时用于排查，敏感凭据会脱敏</span></div>{storage && <code>{storage.rootDir}</code>}</article></section></>;
}
